on:
  push:
    branches: [dev]
jobs:
  build:
    name: create-package
    runs-on: ubutu-latest
    defaults:
      run:
    
    strategy:
      matrix:
        node-version: [16.6]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Use Node.js 16.6
        with:
          node-version: ${{ matrix.node-version}}

      - run: npm ci
      - run: npm run build --if-present
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "AUTO Build: ({sha} {msg})"
        